
export const mockIndustrialPumpReport = {
	manufacturer: 'Grundfos',
	product_name: 'CR 45-3',
	specifications: {
		nominal_flow_m3h: 36.0,
		nominal_head_m: 15.0,
		motor_power_kw: 5.5,
		efficiency_percent: 78,
		material_compatibility: 'Stainless Steel 316, PTFE',
		phase: 3,
		temp_pressure_limits: 'Max Temp: 120°C, Max Pressure: 16 bar',
	},
	replacement_options: [
		{
			manufacturer: 'Grundfos',
			model: 'CR 45-3-2 A-F-A-E HQQE',
			nominal_flow_m3h: 36.0,
			nominal_head_m: 15.5,
			motor_power_kw: 5.5,
			compatibility: 'Direct drop-in replacement',
			notes: 'Same footprint and flange connections. Newer revision with improved seal design.',
		},
		{
			manufacturer: 'Xylem (Lowara)',
			model: 'e-SV 46/3',
			nominal_flow_m3h: 38.0,
			nominal_head_m: 14.8,
			motor_power_kw: 5.5,
			compatibility: 'Compatible with adapter plate',
			notes: 'Slightly higher flow capacity. Requires DN65-to-DN50 adapter on discharge.',
		},
		{
			manufacturer: 'KSB',
			model: 'Movitec VF 45/3-2',
			nominal_flow_m3h: 35.5,
			nominal_head_m: 15.2,
			motor_power_kw: 5.5,
			compatibility: 'Compatible — minor piping adjustment',
			notes: 'Compact design, IE4 motor. May require suction-side spool modification.',
		},
	],
	data_validation_matrix: [
		{
			field: 'Nominal Flow (m³/h)',
			primary_source_value: '36.0',
			validation_source_value: '36.0',
			match: true,
			confidence: 'High',
			notes: 'Both sources agree on nominal flow at BEP.',
		},
		{
			field: 'Nominal Head (m)',
			primary_source_value: '15.0',
			validation_source_value: '15.2',
			match: false,
			confidence: 'Medium',
			notes: 'Minor discrepancy (1.3%). Primary source appears more authoritative (OEM datasheet).',
		},
		{
			field: 'Motor Power (kW)',
			primary_source_value: '5.5',
			validation_source_value: '5.5',
			match: true,
			confidence: 'High',
			notes: 'Consistent across both sources.',
		},
		{
			field: 'Efficiency (%)',
			primary_source_value: '78',
			validation_source_value: '76',
			match: false,
			confidence: 'Medium',
			notes: 'Validation source reports pump-only efficiency; primary source includes motor efficiency.',
		},
		{
			field: 'Material Compatibility',
			primary_source_value: 'SS 316, PTFE',
			validation_source_value: 'SS 316L, PTFE, FKM',
			match: true,
			confidence: 'High',
			notes: 'Core materials match. Validation source lists additional elastomer detail.',
		},
		{
			field: 'Phase',
			primary_source_value: '3',
			validation_source_value: '3',
			match: true,
			confidence: 'High',
			notes: 'Consistent.',
		},
		{
			field: 'Temp / Pressure Limits',
			primary_source_value: '120°C / 16 bar',
			validation_source_value: '120°C / 16 bar',
			match: true,
			confidence: 'High',
			notes: 'Exact match on operating limits.',
		},
	],
	sources: [
		{
			url: 'https://www.chemengjournal.com/pump-selection-guide-2025.pdf',
			title: 'Pump Selection Guide 2025 — ChemEng Journal',
			type: 'Primary',
			reliability: 'High',
			notes: 'Peer-reviewed technical guide with detailed performance curves and material compatibility charts.',
		},
		{
			url: 'https://www.chemicalprocessing.com/articles/2024/optimizing-pump-efficiency',
			title: 'Optimizing Pump Efficiency — Chemical Processing',
			type: 'Validation',
			reliability: 'High',
			notes: 'Industry article with validated efficiency data and real-world case studies.',
		},
		{
			url: 'https://www.pumpsandsystems.com/chemical-process-pumps-overview',
			title: 'Chemical Process Pumps Overview — Pumps & Systems',
			type: 'Reference',
			reliability: 'Medium',
			notes: 'General overview; useful for cross-referencing material specs.',
		},
		{
			url: 'https://www.flowcontrolnetwork.com/industrial-pump-materials.html',
			title: 'Industrial Pump Materials — Flow Control Network',
			type: 'Reference',
			reliability: 'Medium',
			notes: 'Focused on material compatibility for chemical applications.',
		},
		{
			url: 'https://www.engineeringtoolbox.com/centrifugal-pump-curves.html',
			title: 'Centrifugal Pump Curves — Engineering Toolbox',
			type: 'Reference',
			reliability: 'Medium',
			notes: 'Used for sanity-checking pump curve data against nominal specs.',
		},
	],
};

// Mock thought events for simulating the agent's thought process
export const mockThoughtEvents = [
	{ type: 'tool_call', name: 'search_pump_specs', args: { query: 'Grundfos CR 45-3 specifications' } },
	{
		type: 'tool_result',
		name: 'search_pump_specs',
		result: JSON.stringify([
			{ url: 'https://www.chemengjournal.com/pump-selection-guide-2025.pdf' },
			{ url: 'https://www.pumpsandsystems.com/chemical-process-pumps-overview' },
			{ url: 'https://www.flowcontrolnetwork.com/industrial-pump-materials.html' },
			{ url: 'https://www.engineeringtoolbox.com/centrifugal-pump-curves.html' },
			{ url: 'https://www.chemicalprocessing.com/articles/2024/optimizing-pump-efficiency' },
		]),
	},
	{ type: 'tool_call', name: 'read_webpage', args: { url: 'https://www.chemengjournal.com/pump-selection-guide-2025.pdf' } },
	{ type: 'tool_result', name: 'read_webpage', result: 'Page content retrieved' },
	{ type: 'thought', content: 'Analyzing primary source data for Grundfos CR 45-3 specifications...' },
	{ type: 'tool_call', name: 'read_webpage', args: { url: 'https://www.chemicalprocessing.com/articles/2024/optimizing-pump-efficiency' } },
	{ type: 'tool_result', name: 'read_webpage', result: 'Page content retrieved' },
	{ type: 'thought', content: 'Cross-referencing efficiency data from validation source...' },
	{ type: 'thought', content: 'Building data validation matrix and identifying replacement options...' },
];
